Adfs activity cmdlets
AzureAD/MSIdentityTools pull request #24
Opened 2022-10-03 08:14 UTC by marcusca10

These cmdlets allow to create sample SaaS apps to the ADFS server and request tokens to generate server activity. This activity becomes visible under the Azure AD portal if Azure AD Connect Health for AD FS is installed.

2022-10-03 21:39 UTC, jasoth requested changes
There are a few minor updates I think should be made. The larger idea of allowing interactive auth to ADFS does not have to be added now but we should look into doing that.
I assume my Show-MsIdSamlToken command works on the output of your get token commands?

2022-10-03 21:39 UTC, jasoth commented on src/Get-MsIdAdfsSamlToken.ps1
> +  }
Sending credentials directly in the request is not exactly a good practice so I like that it is optional and there is warning. I also think it is fine to leave it in because it can be helpful in troubleshooting and testing.

However, it would be great to add a passive interactive login as the primary option when Windows Integrated Auth is not possible. I have some examples of how we could do that using a popup window or within the browser similar to Show-MsIdSamlToken works. This is probably a larger change so we can merge what you have right now and create a backlog item for the interactive login.

2022-10-03 21:39 UTC, jasoth commented on src/internal/AdfsSamples/AdfsAccessControlPolicy.xml
> +            <Value>12.35.175.1/26</Value>
Should we populate these values in the AdfsSamplePolicy command based on a parameter?

2022-10-03 21:42 UTC, jasoth commented on src/Get-MsIdAdfsSamlToken.ps1
> +  }
The backlog item can be added here so we don't lose track of it. https://github.com/orgs/AzureAD/projects/14

2022-10-04 14:51 UTC, marcusca10 commented on src/internal/Import-AdfsModule.ps1
> +    Gets the form fields to login to AD FS server for the login URL and credentials.
Great catch, nice to have another pair of eyes :)

2022-10-04 14:52 UTC, marcusca10 commented on src/internal/Get-ParsedTokenFromResponse.ps1
> +            $token = $Matches[1] | ConvertFrom-Base64String
Good idea! although the main purpose is not necessarily to get the token, it's nice to have it in a better type than string.

2022-10-04 14:54 UTC, marcusca10 commented on src/Get-MsIdAdfsSamlToken.ps1
> +  }
The main purpose of the cmdlet is to be used within scheduled tasks to send user/app activity via Azure AD Connect Health. I created the backlog item as it should be helpful as additional auth method.

2022-10-04 15:00 UTC, marcusca10 commented on src/internal/Get-ParsedTokenFromResponse.ps1
> +            $token = [System.Web.HttpUtility]::HtmlDecode($Matches[1])
Updated!
I also updated the output to use ConvertFrom-SamlMessage, although it's not a perfect match for SAML the XML is part of the object and better output than string. I also used the same approach for Get-MsIdAdfsWsTrustToken, but has the same issue.
Something to improve in the future, I added both to the backlog.

2022-10-04 15:05 UTC, marcusca10 commented on src/internal/AdfsSamples/AdfsAccessControlPolicy.xml
> +            <Value>12.35.175.1/26</Value>
Great suggestion... found a way to make it work

2022-10-04 15:51 UTC, merged