Adding cmdlet: Update-GuestUserSponsorsFromInvitedBy.ps1
AzureAD/MSIdentityTools pull request #51
Opened 2024-06-10 23:17 UTC by ppolkadots

### Changes proposed in this pull request
- Adding .ps1 file. Will merge to module once testing of the file is complete.

### Testing
- Initial manual test done, no automate testing

### Documentation
- [X] All exported commands have Synopsis, Parameter Descriptions, and at least one Example.

2024-06-13 02:40 UTC, merill requested changes
Good first draft. Please see comments.

2024-06-13 02:40 UTC, merill commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +            $GuestUsers = Get-MgUser -Filter $guestFilter -ExpandProperty Sponsors
This will only retrieve the first 100 users in the tenant. Use -All to get all users

2024-06-13 02:40 UTC, merill commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +        if (!(Test-MgCommandPrerequisites 'Get-Mguser', 'Invoke-MgGraphRequest' -MinimumVersion 2.8.0 -ErrorVariable CriticalError)) { return }
Don't you need Update-MgUser permissions as well?

2024-06-13 02:40 UTC, merill commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +   Update-GuestUserSponsorsFromInvitedBy -All
Please include a description for each example to say what it is doing. See the examples in https://github.com/azuread/msidentitytools/blob/main/src/Export-MsIdAzureMfaReport.ps1

It will also be good to flesh out the synopsis and description with some info. Why would someone need to update the sponsor attribute? Do we have any MSLearn docs to link to?

2024-06-13 02:40 UTC, merill commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +                                $sponsorUrl = ("https://graph.microsoft.com/beta/users/{0}" -f $invitedBy.value.id)
Avoid hard coding the graph base uri and use the Get-GraphBaseUri method.

This is because gov cloud and other clouds have different urls based on the user's sign in context.

2024-06-14 20:12 UTC, ppolkadots commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +            $GuestUsers = Get-MgUser -Filter $guestFilter -ExpandProperty Sponsors
made updates.

2024-06-14 20:16 UTC, ppolkadots commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +        if (!(Test-MgCommandPrerequisites 'Get-Mguser', 'Invoke-MgGraphRequest' -MinimumVersion 2.8.0 -ErrorVariable CriticalError)) { return }
Thanks for point it out - made the change

2024-06-14 20:51 UTC, ppolkadots commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +   Update-GuestUserSponsorsFromInvitedBy -All
done - added links, updated example and description.

2024-06-14 21:00 UTC, ppolkadots commented on src/Update-GuestUserSponsorsFromInvitedBy.ps1
> +                                $sponsorUrl = ("https://graph.microsoft.com/beta/users/{0}" -f $invitedBy.value.id)
Removed hardcode and added below:
(Get-MgEnvironment -Name (Get-MgContext).Environment).GraphEndpoint

2024-06-24 23:51 UTC, merill approved these changes

2024-06-24 23:51 UTC, merged

2024-06-24 23:52 UTC, merill commented
Thanks for the fixes @ppolkadots